[Toc]

# async函数默认返回一个Promise.resolve()

- ```javascript
  async function foo() {
  
  }
  
  foo().then(
      result => {
          console.log('fulfilled:' + result) // fulfilled:undefined
      },
      reason => {
          console.log('rejected:' + reason)
      }
  )
  ```

- async函数默认返回一个Promise.resolve()期约对象, 如果没有显式地return一个值,那么返回Promise.resolve(undefined)

# async会将内部的错误以Promise.reject()包装后返回,或者直接返回Promise.reject()

- ```javascript
  async function bar() {
      throw 333
  }
  
  bar().then(
      result => {
          console.log('fulfilled:' + result)
      },
      reason => {
          console.log('rejected:' + reason) // rejected:333
      }
  )
  ```

- ```javascript
  async function foo() {
      console.log(1)
      return Promise.reject(3)
  }
  
  foo().catch(console.log)
  console.log(2)
  // 1 2 3
  ```

## 返回如下结果会使async判定失败reject

- 内部含有直接使用并且未声明的变量或者函数。
- 内部抛出一个错误`throw new Error`或者返回`reject`状态`return Promise.reject('执行失败')`
- 在`async`里，必须要将结果`return`回来，不然的话不管是执行`reject`还是`resolved`的值都为`undefine`，建议使用箭头函数。

# await

- `await`意思是async wait(异步等待)。这个关键字只能在使用`async`定义的函数里面使用。任何`async`函数都会默认返回`promise`，并且这个`promise`解析的值都将会是这个函数的返回值，而`async`函数必须等到内部所有的 `await` 命令的 `Promise` 对象执行完，才会发生状态改变。

- ```javascript
  async function foo() {
      return await new Promise(resolve => {
          setTimeout(() => {
              resolve(555)
          }, 3000);
      })
  }
  
  foo().then(
      result => {
          console.log('fulfilled:' + result)
          // 3000ms后打印 fulfilled:555
      },
      reason => {
          console.log('rejected:' + reason)
      }
  )
  ```

## await fn()

- await是一个让出线程的标志, await后面的函数会先执行一遍, 然后js引擎将异步代码交给其它浏览器模块处理,js引擎跳出async函数, 执行async函数后面的代码,等到当前执行栈为空后, 开始处理任务队列, 如果await后的函数得到返回值, 那么继续处理async函数后面的代码, 如果没有则开启事件轮询.直到收到await返回值.

- ```javascript
  let count = 0
  
  function timeoutFn(timeout) {
      return new Promise(resolve => {
          if (count === 0) {
              console.log('第0ms:遇见await会直接执行后面的函数, 然后让出跳出async函数的执行栈')
          } else if (count === 1) {
              console.log('第3000ms:接收到第一个await返回的值, 然后才执行第二个await后的函数')
          }
          count++
          return setTimeout(resolve, timeout);
      })
  }
  
  async function foo() {
      await timeoutFn(3000)
      await timeoutFn(4000)
      return '完成'
  }
  console.log('遇见await, 先执行后面的函数代码, 然后跳出async函数, 执行async函数后面的代码')
  foo().then(
      result => {
          console.log(result) // 7000ms后打印 完成
      }
  )
  
  // 遇见await, 先执行后面的函数代码, 然后跳出async函数, 执行async函数后面的代码
  // 第0ms:遇见await会直接执行后面的函数, 然后让出跳出async函数的执行栈
  // 第3000ms:接收到第一个await返回的值, 然后才执行第二个await后的函数
  // 完成
  ```

- ```javascript
  async function foo() {
      console.log('async同步代码')
      await 555
      console.log('异步代码1')
      await 666
      console.log('异步代码2')
      return 777
  }
  foo().then(
      result => {
          console.log(result)
      },
      reason => {
          console.log(reason)
      })
  console.log('跳出async执行后面的代码')
  // async同步代码
  // 跳出async执行后面的代码
  // 异步代码1
  // 异步代码二
  // 777
  ```

- ```javascript
  async function bar() {
      console.log('async 同步代码1')
      await console.log('async 同步代码2')
      await setTimeout(() => {
          console.log('5000ms 后打印1')
      }, 5000)
      console.log('5000ms 后打印2')
  }
  
  bar().then(
      result => {
          console.log(result)
      },
      reason => {
          console.log(reason)
      }
  )
  
  console.log('跳出async 执行后面的代码')
  ```

  - async 同步代码1  ---> 执行流进入async函数,会直接运行函数内的代码, 直到遇见await
  - async 同步代码2  ---> 执行流遇见第一个await, 运行await后面的函数, 然后跳出async函数执行函数后面的代码
  - 跳出async 执行后面的代码  ---> 执行后面的代码
  - 5000ms 后打印2 ---> 收到setTimeout的返回值, 将setTimeout的回调函数丢进事件循环中,继续执行剩下的代码, 即 console.log('5000ms 后打印2')
  - undefined ---> async函数返回的是一个Promise对象, 将该任务加入到当前事件循环tick的任务队列之中, 任务队列执行完毕后才能执行下一个事件循环
  - 5000ms 后打印1 ---> 执行完Promise后,当前tick中的任务队列执行完毕, 执行下一个事件循环

# await 后面跟随 Promise

```javascript
async function foo() {
    const data = await new Promise((resolve,reject) => {
        resolve('haha')
        // reject('haha')
    })
    console.log(typeof data)

}

foo() // string
```

- await 会解包Promise对象, 
- 如果一个await Promise对象是pending状态, 报错
- 如果是fulfilled状态, 得到传入值. 
- 如果是rejected状态,报错
- 问题来源: 通过`const response=await axios.get(...)`可以直接得到服务器返回的数据,无需再调用then方法

- ```javascript
  async function foo() {
      const data = await Promise.resolve('xxx')
      console.log(data)
  
  }
  
  foo()
  ```

